### ISSUE TITLE
rust-xcode-plugin doesn't work

### ISSUE THREAD

**Issue by piaojin** [mtak-/rust-xcode-plugin#1]
Sorry, but rust-xcode-plugin doesn't work.

**Comment by mtak-** [comment]
what xcode version are you using? do you have the xcode command line tools installed?

Can you run this command:
`$ defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID`
and tell me if the UUID is one that is not on this list?
https://github.com/mtak-/rust-xcode-plugin/blob/master/Plug-ins/Rust.ideplugin/Contents/Info.plist

If not I will add it if you are kind enough to share.

Also it may require restarting xcode a few times, then clicking a `Load Bundle` button.

**Comment by piaojin** [comment]
My Xcode version is 9.4.1. I have installed the Xcode command line tools. This is UUID: 426A087B-D3AA-431A-AFDF-F135EC00DE1C. The UUID isn't on the https://github.com/mtak-/rust-xcode-plugin/blob/master/Plug-ins/Rust.ideplugin/Contents/Info.plist list. Maybe you can add my UUID to the list.   Thank you!

**Comment by piaojin** [comment]
I just put the Plug-ins and Specifications folders in /Users/User name/Library/Developer/Xcode/. Is it right?

**Comment by piaojin** [comment]
Hi @mtak- . I have solved this problem. I follow your suggestion of adding my UUID to the Plug-ins/Rust.ideplugin/Contents/Info.plist. And then restart Xcode then clicking a Load Bundle button. Finally, it works. So nice, I can set breakpoints in the GUI.  It is better if the `rust-xcode-plugin` support rust code hinting. I know it is hard so it may be a good wish. Thank you for your help.

**Comment by mtak-** [comment]
@piaojin Thank you! I'm sure there are others on 9.4.1 who will benefit from that. I suspect hinting/autocomplete will be hard to get support for in xcode unfortunately. I do most of my development in VSCode and use xcode only for debugging.

Unrelated: I've added this to my `~/.lldbinit` file to help with rust debugging, but it's crashes the debugger sometimes. Do you have the same experience?

```lldb
command script import "~/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/etc/lldb_rust_formatters.py"
type summary add --no-value --python-function lldb_rust_formatters.print_val -x ".*" --category Rust
type category enable Rust
```

**Comment by piaojin** [comment]
@mtak- Sorry, I haven't use Xcode to debug rust for some times. So I didn't have the same experience.  I will try your command script.
